steps:
  # Puedes incluir otros pasos aquí según tus necesidades, como la construcción de tu código.
  # Por ejemplo, si estás utilizando un marco de trabajo como Express.js, necesitarás un paso para construir tu aplicación.
  # crear api config
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'api-gateway'
      - 'api-configs'
      - 'create'
      - '$_API_NAME-$SHORT_SHA' 
      - '--api=$_APIGATEWAY_NAME' 
      - '--openapi-spec=api-gateway.yaml'


  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'api-gateway'
      - 'gateways'
      - 'update'
      - 'sapiencia-api-gateway-dev'
      - '--location=us-central1'
      - '--display-name=$_API_NAME-$SHORT_SHA'
      - '--api-config=$_API_NAME-$SHORT_SHA' 
      - '--api=$_APIGATEWAY_NAME' 
    


