steps:
  # Puedes incluir otros pasos aquí según tus necesidades, como la construcción de tu código.
  # Por ejemplo, si estás utilizando un marco de trabajo como Express.js, necesitarás un paso para construir tu aplicación.



  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'api-gateway'
      - 'gateways'
      - 'update'
      - 'sapiencia-api-gateway-dev'
      - '--location=us-central1'
      - '--display-name="sapiencia-api-gateway-dev-v4'
      - '--api-config=sapiencia-api-gateway-dev-49871dc' 
      - '--api=sapiencia-api-gateway-dev' 
    


