steps:
  # Puedes incluir otros pasos aquí según tus necesidades, como la construcción de tu código.
  # Por ejemplo, si estás utilizando un marco de trabajo como Express.js, necesitarás un paso para construir tu aplicación.

  # crear api config
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'api-gateway'
      - 'api-configs'
      - 'create'
      - 'sapiencia-api-gateway-dev-$SHORT_SHA' 
      - '--api=sapiencia-api-gateway-dev' 
      - '--openapi-spec=api-gateway.yaml'

  # Paso para esperar (dormir)
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sleep 10 # Pausa de 10 segundos

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'api-gateway'
      - 'gateways'
      - 'update'
      - 'sapiencia-api-gateway-dev'
      - '--location=us-central1'
      - '--display-name="sapiencia-api-gateway-dev-$SHORT_SHA'
      - '--api-config=sapiencia-api-gateway-dev-$SHORT_SHA'
      - 'sapiencia-api-gateway-dev-$SHORT_SHA' 
      - '--api=sapiencia-api-gateway-dev' 
    


