steps:

  # crear api config
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'api-gateway'
      - 'api-configs'
      - 'create'
      - '$_API_NAME-$SHORT_SHA' 
      - '--api=$_APIGATEWAY_NAME' 
      - '--openapi-spec=api-gateway.yaml'

  # actualizar la apigateway
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'api-gateway'
      - 'gateways'
      - 'update'
      - 'sapiencia-api-gateway-dev'
      - '--location=us-central1'
      - '--display-name=$_API_NAME-$SHORT_SHA'
      - '--api-config=$_API_NAME-$SHORT_SHA' 
      - '--api=$_APIGATEWAY_NAME' 
    


