# openapi2-run.yaml
swagger: '2.0'
info:
  title: api-gateway
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- https
produces:
- application/json
paths:
  /api/v1/auth/signin:
    post:
      x-google-backend:
        address: https://sapiencia-auth-api-ukyunq2uxa-uc.a.run.app/api/v1/auth/signin
      responses:
        '200':
          description: A successful response
          schema:
            type: string